### ISSUE TITLE
Permissions are incorrect on initial setup

### ISSUE THREAD

**Issue by mcparlandjcgi** [jhermann/dependency-check-py#2]
When I attempted to run this as part of a Jenkins pipeline I had the following error;

```
Traceback (most recent call last):
  File "/srv/jenkins/venv/myproject/bin/dependency-check", line 7, in <module>
    from dependency_check import run
  File "/srv/jenkins/venv/myproject/lib64/python3.6/site-packages/dependency_check.py", line 77
    os.chmod(os.path.join(dc_home, 'bin', 'dependency-check.sh'), 0755)
                                                                     ^
SyntaxError: invalid token
```

This was running on a CentOS machine, with Python 3.6 installed.  `dependency-check` was installed via
`pip3 install -r requirements.txt`
where `requirements.txt` included `dependency-check`.

**Comment by jhermann** [comment]
Already fixed a while ago, watch out for a 0.2.0 release.
