### ISSUE TITLE
Option to produce both XML and HTML report

### ISSUE THREAD

**Issue by wkoot** [jhermann/dependency-check-py#4]
I currently run `dependency-check` twice, to obtain both xml and html report for usage in sonar:
```
dependency-check --format XML --out reports/dependency-check.xml
dependency-check --format HTML --out reports/dependency-check.html
```
This is advised by the [Dependency-Check Sonar plugin configuration](https://github.com/stevespringett/dependency-check-sonar-plugin#plugin-configuration)

It would be nice to be able to generate both at once, while retaining the option to specify output filename(prefix).

**Comment by jhermann** [comment]
I merely pass on any options, so you have to place this upstream with the OWASP project.
