### ISSUE TITLE
PyPi version obsolete

### ISSUE THREAD

**Issue by jeffchamblee** [jhermann/dependency-check-py#5]
I have been getting dependency check from PyPi (https://pypi.org/project/dependency-check/). Now I realize that the version is very old (0.2.0). How can I get an up to date version in a Python environment? I'd like to continue using pip because I need to install it automatically in a continuous integration pipeline.

**Comment by davewichers** [comment]
When do you plan to release a new version that supports the 5.x version of DependencyCheck? or can the 0.2.0 version be configured to use the latest version of DC and does it work properly? DC 5.x requires the JSON NIST feed, rather than the old XML feed.
