### ISSUE TITLE
not able  to  analys python code 

### ISSUE THREAD

**Issue by szemmour-rh** [jhermann/dependency-check-py#6]
i'm trying  to scan the python  dependency but  it  shows nothing.

the  testing  python code  is :  https://github.com/jhermann/dependency-check-py.git

./dependency-check --disableAssembly -s .  -o build --project "$(python ./setup.py --name)"  --enableExperimental  --log odc.log && xdg-open ../build/dependency-check-report.html

the  html report  shows  :

Project: app
Scan Information (show less):

    dependency-check version: 5.2.4
    Report Generated On: Tue, 4 Feb 2020 17:29:22 -0500
    Dependencies Scanned: 0 (0 unique)
    Vulnerable Dependencies: 0
    Vulnerabilities Found: 0
    Vulnerabilities Suppressed: 0
    NVD CVE Checked: 2020-02-04T17:29:08
    NVD CVE Modified: 2020-02-04T16:02:04
    VersionCheckOn: 2020-02-04T17:29:08

apparently  its not able to detect  the dependencies.

Is  there a specific any details  that need  to  be in the  repo in  order to be  scanned correctly ?

**Comment by jhermann** [comment]
Use a test project that actually HAS any dependencies.
